"""Redraw the survey's own data figures as PGF/TikZ, in the restrained palette academic papers use.

These replace the coloured SVGs of the markdown edition. The rules are: greyscale plus one muted
accent, no gradients, no rounded boxes, thin rules, and text in the document's own font so a
figure looks like part of the page rather than a screenshot. Every number is recomputed from
corpus/rows at build time.
"""
import json, glob, re, sys
from collections import Counter
from pathlib import Path
R = Path(__file__).resolve().parents[1]
OUT = R / "tex/figs"; OUT.mkdir(parents=True, exist_ok=True)
ROWS = [json.load(open(f)) for f in glob.glob(str(R / "corpus/rows/*.json"))]
M = [r for r in ROWS if r.get("class") == "method"]
N = len(M)

PRE = r"""% generated by tools/make_tikz_figures.py; do not edit
\begin{tikzpicture}[
  font=\footnotesize,
  bar/.style={draw=none,fill=black!62},
  barlight/.style={draw=none,fill=black!22},
  baracc/.style={draw=none,fill=accent},
  box/.style={draw=black!45,line width=0.3pt,inner sep=3pt,align=left},
  ghost/.style={draw=black!35,line width=0.3pt,dash pattern=on 1.4pt off 1.4pt,inner sep=3pt,align=left},
  lnk/.style={draw=black!38,line width=0.28pt},
  lbl/.style={font=\scriptsize},
  num/.style={font=\scriptsize\color{black!55}},
]
"""

def esc(s): return str(s).replace("_", r"\_").replace("%", r"\%").replace("&", r"\&")

def hbar_chart(rows, total, width=6.4, rowsep=0.36, accent_when=None, note=None):
    """rows: list of (label, value). Returns tikz body."""
    mx = max(v for _, v in rows) or 1
    out = [PRE]
    y = 0.0
    for label, v in rows:
        w = width * v / mx
        style = "baracc" if (accent_when and accent_when(label, v)) else "bar"
        out.append(rf"\node[lbl,anchor=east] at (0,{-y:.2f}) {{{esc(label)}}};")
        out.append(rf"\fill[{style}] (0.12,{-y-0.085:.2f}) rectangle ({0.12+w:.2f},{-y+0.085:.2f});")
        out.append(rf"\node[num,anchor=west] at ({0.12+w+0.1:.2f},{-y:.2f}) {{{v}}};")
        y += rowsep
    out.append(r"\end{tikzpicture}")
    return "\n".join(out)

def fig_hands():
    """Figure 2: method rows per hand, on the pattern set tools/make_tables.py owns.

    The label is this edition's wording; the count is not this figure's to define. It used to be:
    the bar merged Shadow with Adroit and printed 24 against the 21 in the sentence under the
    caption, and LEAP read 12 here against 11 in the table. Both now come from make_tables.USES.
    """
    from make_tables import uses_pattern
    canon = [("Allegro", "allegro_hand_v4_2016"), ("Shadow", "shadow_dexterous_hand_2005"),
             ("Inspire", "inspire_rh56dfx_2023"), ("LEAP", "leap_hand_2023"),
             ("parallel-jaw gripper", "gripper"), ("Ability", "psyonic_ability_hand_2021"),
             ("XHand", "robotera_xhand1_2024"), ("Sharpa", "sharpa_wave_2026"),
             ("Adroit in simulation", "adroit"), ("Fourier", "fourier"), ("Wuji", "wuji_hand_2025"),
             ("D'Claw or TriFinger", "dclaw_trifinger"), ("Faive", "faive_hand_2023")]
    canon = [(label, uses_pattern(slug)) for label, slug in canon]
    c = Counter()
    for r in M:
        h = str(r.get("hand") or "")
        for name, pat in canon:
            if re.search(pat, h, re.I): c[name] += 1
    rows = [(n, v) for n, v in c.most_common() if v]
    body = hbar_chart(rows, N, accent_when=lambda l, v: "gripper" in l)
    (OUT / "fig_hands.tex").write_text(body)
    return len(rows)

# fig_reporting() used to live here. It is written by tools/make_finding_figures.py now, with the
# bars ordered and the two quantities a reader needs in order to compare two methods marked, so that
# one generator owns every figure that carries a headline finding. Two generators writing one file
# is how a figure comes back from the dead.


def fig_field():
    """Figure 1: the routes through the field, as a five-column flow. Two-column float."""
    import re
    def norm(s):
        s = (s or "").lower()
        if any(k in s for k in ("isaac lab","isaaclab","isaac sim","isaacsim","orbit")): return "Isaac Lab or Sim"
        if "isaac" in s: return "Isaac Gym"
        if "mjx" in s or "mujoco" in s: return "MuJoCo"
        if "sapien" in s or "maniskill" in s: return "SAPIEN"
        if not s or "not stated" in s: return "not stated"
        if s in ("none","no simulator"): return "no simulator"
        return "other"
    human = sum(1 for r in M if r.get("human_data") and str(r["human_data"]).lower() not in ("none","no"))
    nodem = sum(1 for r in M if str(r.get("human_data") or "").lower() in ("none","no"))
    cols = [
      ("data source", [("human data named", human, 0), ("no demonstrations", nodem, 0),
                       ("not stated", N - human - nodem, 1)]),
      ("embodiment", [("one hand", sum(1 for r in M if r.get("bimanual") is False), 0),
                      ("two hands", sum(1 for r in M if r.get("bimanual") is True), 0),
                      ("not stated", sum(1 for r in M if r.get("bimanual") is None), 1)]),
      ("simulator", [(k, v, 1 if k == "not stated" else 0)
                     for k, v in Counter(norm(r.get("sim")) for r in M).most_common(6)]),
      ("training", [(k, v, 0) for k, v in Counter(p for r in M for p in (r.get("paradigm") or [])).most_common(6)]),
      ("evaluation", [("real robot", sum(1 for r in M if r.get("real_robot") is True), 0),
                      ("simulation only", sum(1 for r in M if r.get("real_robot") is not True), 0),
                      ("penetration addressed",
                       sum(1 for r in M if r.get("penetration") in ("penalised","measured","constrained")), 2),
                      ("penetration silent", sum(1 for r in M if r.get("penetration") == "not addressed"), 2)]),
    ]
    cw, gap, top = 3.05, 0.42, 0.0
    mx = max(v for _, items in cols for _, v, _ in items) or 1
    out = [PRE.replace("font=\\footnotesize", "font=\\scriptsize")]
    pos = {}
    for ci, (cname, items) in enumerate(cols):
        x = ci * (cw + gap)
        out.append(rf"\node[font=\scriptsize\bfseries] at ({x+cw/2:.2f},0.42) {{{esc(cname)}}};")
        y = 0.0
        for name, v, kind in items:
            h = max(0.34, 0.26 + 0.62 * v / mx)
            sty = {0: "box", 1: "ghost", 2: "box"}[kind]
            extra = ",fill=accent!8,draw=accent!60" if kind == 2 else ""
            out.append(rf"\draw[{sty}{extra}] ({x:.2f},{-y:.2f}) rectangle ({x+cw:.2f},{-y-h:.2f});")
            out.append(rf"\node[lbl,anchor=west] at ({x+0.08:.2f},{-y-h/2:.2f}) {{{esc(name)}}};")
            out.append(rf"\node[num,anchor=east] at ({x+cw-0.08:.2f},{-y-h/2:.2f}) {{{v}}};")
            pos[(ci, name)] = (x, -y - h / 2, h)
            y += h + 0.13
    for ci in range(len(cols) - 1):
        for (c, n), (x, yy, h) in pos.items():
            if c != ci: continue
            for (c2, n2), (x2, y2, h2) in pos.items():
                if c2 != ci + 1: continue
                w = max(0.12, min(1.0, 2.2 * (h * h2) / 1.2))
                out.append(rf"\draw[lnk,line width={w:.2f}pt] ({x+cw:.2f},{yy:.2f}) .. controls "
                           rf"({x+cw+0.2:.2f},{yy:.2f}) and ({x2-0.2:.2f},{y2:.2f}) .. ({x2:.2f},{y2:.2f});")
    out.append(r"\end{tikzpicture}")
    (OUT / "fig_field.tex").write_text("\n".join(out))
    return sum(len(i) for _, i in cols)

if __name__ == "__main__":
    print("hands rows:", fig_hands())
    print("field nodes:", fig_field())
    print("method rows:", N)
