"""Redraw the survey's own data figures as PGF/TikZ, in the restrained palette academic papers use.

These replace the coloured SVGs of the markdown edition. The rules are: greyscale plus one muted
accent, no gradients, no rounded boxes, thin rules, and text in the document's own font so a
figure looks like part of the page rather than a screenshot. Every number is recomputed from
corpus/rows at build time.
"""
import json, glob, re, sys
from collections import Counter
from pathlib import Path
R = Path(__file__).resolve().parents[1]
OUT = R / "tex/figs"; OUT.mkdir(parents=True, exist_ok=True)
ROWS = [json.load(open(f)) for f in glob.glob(str(R / "corpus/rows/*.json"))]
M = [r for r in ROWS if r.get("class") == "method"]
N = len(M)

PRE = r"""% generated by tools/make_tikz_figures.py; do not edit
\begin{tikzpicture}[
  font=\footnotesize,
  bar/.style={draw=none,fill=black!62},
  barlight/.style={draw=none,fill=black!22},
  baracc/.style={draw=none,fill=accent},
  box/.style={draw=black!45,line width=0.3pt,inner sep=3pt,align=left},
  ghost/.style={draw=black!35,line width=0.3pt,dash pattern=on 1.4pt off 1.4pt,inner sep=3pt,align=left},
  lnk/.style={draw=black!38,line width=0.28pt},
  lbl/.style={font=\scriptsize},
  num/.style={font=\scriptsize\color{black!55}},
]
"""

def esc(s): return str(s).replace("_", r"\_").replace("%", r"\%").replace("&", r"\&")

def wrap(text, width):
    """Greedy wrap on word boundaries, into lines of at most `width` characters."""
    lines, cur = [], ""
    for word in text.split():
        if cur and len(cur) + 1 + len(word) > width:
            lines.append(cur)
            cur = word
        else:
            cur = f"{cur} {word}".strip()
    if cur:
        lines.append(cur)
    return lines


# The chart's row label. A table prints "Inspire Robots RH56DFX"; a bar three centimetres long
# cannot, so each hand carries a short name here. Every key of the corpus's 33 hand rows must
# appear, and fig_hands asserts it, so a hand added to the corpus stops this generator rather
# than being drawn under its filename.
SHORT = {
    "allegro_hand_v4_2016": "Allegro", "shadow_dexterous_hand_2005": "Shadow",
    "inspire_rh56dfx_2023": "Inspire RH56", "robotera_xhand1_2024": "XHand",
    "psyonic_ability_hand_2021": "Ability Hand", "sharpa_wave_2026": "SharpaWave",
    "wuji_hand_2025": "Wuji", "agibot_omnihand_2025": "AgiBot OmniHand",
    "brainco_revo2_2025": "BrainCo Revo 2", "shadow_dex_ee_2024": "DEX-EE",
    "linkerbot_l20_2025": "Linker Hand", "tesollo_dg5f_2024": "Tesollo DG-5F",
    "unitree_dex5_2025": "Unitree Dex5", "proception_prohand_2026": "Proception ProHand",
    "leap_hand_2023": "LEAP", "bidexhand_2025": "BiDexHand",
    "dexhand_open_source_2023": "DexHand", "orca_hand_2025": "ORCA", "ruka_2025": "RUKA",
    "ruka_v2_2026": "Ruka-v2", "leap_hand_v2_adv_2025": "LEAP Hand V2",
    "faive_hand_2023": "Faive", "ilda_hand_2021": "ILDA", "pisa_iit_softhand_2014": "Pisa/IIT",
    "boston_dynamics_atlas_hand_2026": "Atlas hand", "clone_robotics_hand_2024": "Clone",
    "daxo_muscle_v0_2025": "Daxo Muscle", "figure_03_hand_2025": "Figure 03",
    "onex_neo_hand_2026": "1X NEO", "paxini_dexh13_2024": "PaXini DexH13",
    "sanctuary_phoenix_hand_2024": "Sanctuary Phoenix", "tesla_optimus_hand_2025": "Tesla Optimus",
    "xiaomi_cyberone_hand_2026": "Xiaomi CyberOne",
}

# The five names that carry the field. Kept as one list because the figure's headline strip counts
# the method rows that name ANY of them, which is not the sum of their bars: seven rows name two.
BIG = ["allegro_hand_v4_2016", "shadow_dexterous_hand_2005", "adroit", "inspire_rh56dfx_2023",
       "leap_hand_2023"]


def fig_hands():
    """Which hands the literature runs on, and which hands it does not run on at all.

    Two things have to land. The first is concentration: five names cover three quarters of the
    method rows that name a hand. The second is absence, and a ranked bar chart cannot state it,
    because a hand no paper uses has no bar and simply is not there. So every tabulated hand
    appears, the ones with no method row as named slots in a shaded shelf with a zero where their
    bar would be, and the rows are banded by how the hand can be got: sold, open hardware,
    a research prototype, or a company announcement. The last band has no bars at all.

    Counts come from make_tables.USES, the one pattern set for `method rows whose own experiments
    use this hand`, and the used/unused partition is checked against tools/hand_usage.py, which is
    the rule the prose and the appendix quote.
    """
    from make_tables import uses_pattern, USES
    from hand_usage import partition

    hands = [r for r in ROWS if r.get("class") == "hand"]
    bib = {e["key"]: e for e in json.load(open(R / "corpus/bib.json"))}
    hand_field = [str(r.get("hand") or "") for r in M]

    def count(pat):
        return sum(1 for h in hand_field if re.search(pat, h, re.I))

    def band_of(h):
        """Sold, open hardware, research prototype, or announced by a company.

        The first split is Table~IV against Table~V and is make_tables' own rule. Inside Table V
        the split is the bibliography's venue: a hand whose only source is a product page or a
        company announcement is an announcement, and one with a paper behind it is a prototype.
        """
        if h.get("release_status") in ("announced", "prototype", "internal-only"):
            venue = str(bib.get(h["key"], {}).get("venue") or "")
            company = re.search(r"company announcement|commercial product", venue, re.I)
            return "company" if company else "proto"
        return "open" if h.get("release_status") == "open-source" else "sold"

    missing = {h["key"] for h in hands} - set(SHORT)
    if missing:
        sys.exit(f"fig_hands has no short name for {sorted(missing)}")

    banded = {k: [] for k in ("sold", "open", "proto", "company")}
    for h in hands:
        banded[band_of(h)].append((SHORT[h["key"]], count(USES[h["key"]])))
    for v in banded.values():
        v.sort(key=lambda t: (-t[1], t[0].lower()))

    # the partition this figure draws has to be the partition the prose quotes
    p = partition()
    used = sum(1 for v in banded.values() for _, n in v if n)
    unused = sum(1 for v in banded.values() for _, n in v if not n)
    if (used, unused, len(hands)) != (p["used"], p["unused"], p["hands"]):
        sys.exit(f"fig_hands and tools/hand_usage.py disagree: figure says {used} used and "
                 f"{unused} unused of {len(hands)}, the rule says {p['used']} and {p['unused']} "
                 f"of {p['hands']}. Reconcile before the figure is drawn.")

    extras = [("parallel-jaw gripper", "gripper"), ("Adroit (Shadow in MuJoCo)", "adroit"),
              ("Fourier", "fourier"), ("D'Claw or TriFinger", "dclaw_trifinger")]
    extras = sorted(((lab, count(uses_pattern(slug))) for lab, slug in extras), key=lambda t: -t[1])

    named = sum(1 for h in hand_field if h.strip())
    big = sum(1 for h in hand_field
              if any(re.search(uses_pattern(k), h, re.I) for k in BIG))

    # --- geometry ---------------------------------------------------------------------------
    W, x0, xmax = 8.00, 2.42, 7.30
    pitch, bh = 0.265, 0.17
    top = max(n for v in banded.values() for _, n in v)
    sc = (xmax - x0) / top
    out = [PRE]
    y = 0.0

    # the headline: the 103 rows that name a hand, split by whether they name one of the five
    wbig = W * big / named
    out.append(rf"\fill[bar] (0,{y:.2f}) rectangle ({wbig:.2f},{y - 0.34:.2f});")
    out.append(rf"\fill[barlight] ({wbig:.2f},{y:.2f}) rectangle ({W:.2f},{y - 0.34:.2f});")
    out.append(rf"\node[font=\scriptsize\color{{white}},anchor=west] at (0.10,{y - 0.17:.2f}) "
               rf"{{\textbf{{{big}}} of the {named} rows that name a hand name one of five}};")
    out.append(rf"\node[font=\scriptsize\color{{black!60}},anchor=east] at ({W - 0.10:.2f},"
               rf"{y - 0.17:.2f}) {{{named - big}}};")
    y -= 0.34 + 0.30
    out.append(rf"\node[font=\scriptsize\color{{black!55}},anchor=west] at (0,{y:.2f}) "
               rf"{{bars: method papers whose own experiments use the hand}};")
    y -= 0.30

    def band(title, rows, note=None):
        nonlocal y
        out.append(rf"\draw[lnk] (0,{y:.2f}) -- ({W:.2f},{y:.2f});")
        y -= 0.06
        out.append(rf"\node[font=\scriptsize\bfseries,anchor=north west] at (0,{y:.2f}) "
                   rf"{{{esc(title)}}};")
        if note:
            out.append(rf"\node[font=\scriptsize\color{{black!55}},anchor=north east] at "
                       rf"({W:.2f},{y:.2f}) {{{esc(note)}}};")
        y -= 0.50
        bars = [(lab, n) for lab, n in rows if n]
        zeros = [lab for lab, n in rows if not n]
        for lab, n in bars:
            out.append(rf"\node[lbl,anchor=east] at ({x0 - 0.10:.2f},{y:.2f}) {{{esc(lab)}}};")
            out.append(rf"\fill[bar] ({x0:.2f},{y - bh / 2:.2f}) rectangle "
                       rf"({x0 + sc * n:.2f},{y + bh / 2:.2f});")
            out.append(rf"\node[num,anchor=west] at ({x0 + sc * n + 0.10:.2f},{y:.2f}) {{{n}}};")
            y -= pitch
        if zeros:
            lines = wrap("no method paper runs on: " + ", ".join(zeros), 60)
            h = 0.15 + 0.235 * len(lines)
            ytop = y + pitch / 2 - 0.04
            out.append(rf"\fill[wash] (0,{ytop:.2f}) rectangle ({W:.2f},{ytop - h:.2f});")
            out.append(rf"\node[font=\scriptsize\color{{black!60}},anchor=north west,align=left] "
                       rf"at (0.08,{ytop - 0.04:.2f}) "
                       rf"{{" + r"\\".join(esc(l) for l in lines) + r"};")
            out.append(rf"\node[font=\normalsize\bfseries\color{{accent}},anchor=east] at "
                       rf"({W - 0.06:.2f},{ytop - h / 2:.2f}) {{0}};")
            y = ytop - h - 0.10

    band("sold", banded["sold"], f"{len(banded['sold'])} hands")
    band("open hardware", banded["open"], f"{len(banded['open'])} hands")
    band("research prototype, not purchasable", banded["proto"],
         f"{len(banded['proto'])} hands")
    band("announced by a company, not purchasable", banded["company"],
         f"{len(banded['company'])} hands")
    band("platforms with no row in the hand tables", extras, "4 of them")
    out.append(rf"\draw[lnk] (0,{y + pitch / 2:.2f}) -- ({W:.2f},{y + pitch / 2:.2f});")
    out.append(rf"\node[font=\scriptsize\color{{black!55}},anchor=north west] at "
               rf"(0,{y + pitch / 2 - 0.08:.2f}) {{{len(hands)} hands tabulated, "
               rf"{unused} of them with no method row at all}};")
    out.append(r"\end{tikzpicture}")
    (OUT / "fig_hands.tex").write_text("\n".join(out) + "\n")
    return len(hands), used, unused, big, named


# fig_reporting() used to live here. It is written by tools/make_finding_figures.py now, with the
# bars ordered and the two quantities a reader needs in order to compare two methods marked, so that
# one generator owns every figure that carries a headline finding. Two generators writing one file
# is how a figure comes back from the dead.


def fig_field():
    """The routes through the field, as a five-column flow. Two-column float.

    A node is a predicate over the method rows, and its count is that predicate applied; an edge
    between two adjacent nodes is the number of rows satisfying both. Edges used to be drawn
    between every pair of adjacent nodes with a width taken from the two boxes' heights, which
    made the picture a hairball and made its caption false: it claimed the corpus's own routes.
    A route no row takes is now not drawn at all, and a route's width is the rows that take it.
    """
    def norm(s):
        s = (s or "").lower()
        if any(k in s for k in ("isaac lab", "isaaclab", "isaac sim", "isaacsim", "orbit")):
            return "Isaac Lab or Sim"
        if "isaac" in s: return "Isaac Gym"
        if "mjx" in s or "mujoco" in s: return "MuJoCo"
        if "sapien" in s or "maniskill" in s: return "SAPIEN"
        if not s or "not stated" in s: return "not stated"
        if s in ("none", "no simulator"): return "no simulator"
        return "other"

    def human(r):
        v = str(r.get("human_data") or "").lower()
        return bool(r.get("human_data")) and v not in ("none", "no")

    def nodem(r):
        return str(r.get("human_data") or "").lower() in ("none", "no")

    HANDLED = ("penalised", "measured", "constrained")
    sims = [k for k, _ in Counter(norm(r.get("sim")) for r in M).most_common(6)]
    pars = [k for k, _ in Counter(p for r in M for p in (r.get("paradigm") or [])).most_common(6)]
    cols = [
        ("data source", [("human data named", human, 0),
                         ("no demonstrations", nodem, 0),
                         ("not stated", lambda r: not human(r) and not nodem(r), 1)]),
        ("embodiment", [("one hand", lambda r: r.get("bimanual") is False, 0),
                        ("two hands", lambda r: r.get("bimanual") is True, 0),
                        ("not stated", lambda r: r.get("bimanual") is None, 1)]),
        ("simulator", [(k, (lambda k: lambda r: norm(r.get("sim")) == k)(k),
                        1 if k == "not stated" else 0) for k in sims]),
        ("training", [(k, (lambda k: lambda r: k in (r.get("paradigm") or []))(k), 0)
                      for k in pars]),
        ("evaluation", [("real robot", lambda r: r.get("real_robot") is True, 0),
                        ("simulation only", lambda r: r.get("real_robot") is not True, 0),
                        ("penetration addressed",
                         lambda r: r.get("penetration") in HANDLED, 2),
                        ("penetration silent",
                         lambda r: r.get("penetration") == "not addressed", 2)]),
    ]
    count = {(ci, name): sum(1 for r in M if pred(r))
             for ci, (_, items) in enumerate(cols) for name, pred, _ in items}

    # --- layout, computed before anything is drawn so the edges can go underneath the boxes ---
    # the gap is where the routes are read, so it is wide enough to see a width in
    cw, gap = 2.92, 0.88
    mx = max(count.values()) or 1
    pos, geo = {}, {}
    for ci, (cname, items) in enumerate(cols):
        x = ci * (cw + gap)
        y = 0.0
        for name, _, kind in items:
            v = count[(ci, name)]
            h = max(0.34, 0.26 + 0.62 * v / mx)
            pos[(ci, name)] = (x, -y - h / 2, h)
            geo[(ci, name)] = (x, -y, h, kind, v)
            y += h + 0.13

    out = [PRE.replace("font=\\footnotesize", "font=\\scriptsize")]
    # --- the routes the corpus actually contains ---------------------------------------------
    edges = []
    for ci in range(len(cols) - 1):
        for a, pa, _ in cols[ci][1]:
            for b, pb, _ in cols[ci + 1][1]:
                n = sum(1 for r in M if pa(r) and pb(r))
                if n:
                    edges.append((ci, a, b, n))
    mxe = max(n for *_, n in edges) or 1
    for ci, a, b, n in sorted(edges, key=lambda e: e[3]):
        x, yy, _ = pos[(ci, a)]
        x2, y2, _ = pos[(ci + 1, b)]
        w = 0.10 + 1.30 * n / mxe
        shade = 14 + int(34 * n / mxe)
        out.append(rf"\draw[draw=black!{shade},line width={w:.2f}pt] ({x + cw:.2f},{yy:.2f}) "
                   rf".. controls ({x + cw + 0.45:.2f},{yy:.2f}) and ({x2 - 0.45:.2f},{y2:.2f}) "
                   rf".. ({x2:.2f},{y2:.2f});")
    # --- the nodes, on top of them ------------------------------------------------------------
    for ci, (cname, items) in enumerate(cols):
        x = ci * (cw + gap)
        out.append(rf"\node[font=\scriptsize\bfseries] at ({x + cw / 2:.2f},0.42) {{{esc(cname)}}};")
        for name, _, _ in items:
            xx, ytop, h, kind, v = geo[(ci, name)]
            sty = {0: "box", 1: "ghost", 2: "box"}[kind]
            extra = ",fill=accent!8,draw=accent!60" if kind == 2 else ",fill=white"
            out.append(rf"\draw[{sty}{extra}] ({xx:.2f},{ytop:.2f}) rectangle "
                       rf"({xx + cw:.2f},{ytop - h:.2f});")
            out.append(rf"\node[lbl,anchor=west] at ({xx + 0.08:.2f},{ytop - h / 2:.2f}) "
                       rf"{{{esc(name)}}};")
            out.append(rf"\node[num,anchor=east] at ({xx + cw - 0.08:.2f},{ytop - h / 2:.2f}) "
                       rf"{{{v}}};")
    out.append(r"\end{tikzpicture}")
    (OUT / "fig_field.tex").write_text("\n".join(out) + "\n")
    return len(pos), len(edges)


if __name__ == "__main__":
    print("hands: %d tabulated, %d used, %d with no method row; %d of %d rows name one of five" % fig_hands())
    print("field: %d nodes, %d routes the corpus contains" % fig_field())
    print("method rows:", N)
